//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCAAFootballPlayoffs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordID { get; set; }
        public short Wins { get; set; }
        public short Losses { get; set; }
        public int SeasonID { get; set; }
        public int TeamID { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Season Season { get; set; }
    }
}
